# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longtude', models.FloatField()),
                ('Ideal_SoilMoisture', models.IntegerField()),
                ('Ideal_pH', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('min_water', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='tank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.Tank'),
        ),
    ]
