# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_Moisture', models.IntegerField()),
                ('pH', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tank_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tankWaterLevel', models.IntegerField()),
                ('tankID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.Tank')),
            ],
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='Ideal_SoilMoisture',
            new_name='ideal_SoilMoisture',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='Ideal_pH',
            new_name='ideal_pH',
        ),
        migrations.AddField(
            model_name='plant_details',
            name='plantID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.Plant'),
        ),
    ]
