# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0002_auto_20171004_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_supplied', models.IntegerField()),
                ('plantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.Plant')),
            ],
        ),
    ]
