# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0003_actuator'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='average_pH',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plant',
            name='average_soilMoisture',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='water_supplied',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plant',
            name='ideal_SoilMoisture',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plant',
            name='ideal_pH',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='plant',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='plant',
            name='longtude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='plant_details',
            name='pH',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='plant_details',
            name='soil_Moisture',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tank',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tank',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tank',
            name='min_water',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tank_details',
            name='tankWaterLevel',
            field=models.IntegerField(default=0),
        ),
    ]
