# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 03:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0004_auto_20171005_0245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plant_Details',
            new_name='Plant_Data',
        ),
        migrations.RenameModel(
            old_name='Tank_Details',
            new_name='Tank_Data',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='average_pH',
            new_name='averageSoilMoisture',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='average_soilMoisture',
            new_name='averagepH',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='ideal_SoilMoisture',
            new_name='idealSoilMoisture',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='ideal_pH',
            new_name='idealpH',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='longtude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='plant_data',
            old_name='soil_Moisture',
            new_name='soilMoisture',
        ),
    ]
