# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0006_auto_20171005_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='user',
        ),
    ]
