# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0013_userprofile_contactno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='idealSoilMoisture',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='idealpH',
        ),
    ]
