# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0015_auto_20171102_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actuator',
            name='plantID',
        ),
        migrations.RemoveField(
            model_name='actuator',
            name='user',
        ),
        migrations.AlterField(
            model_name='plant',
            name='latitude',
            field=models.FloatField(default=13.7021),
        ),
        migrations.AlterField(
            model_name='plant',
            name='longitude',
            field=models.FloatField(default=80.0181),
        ),
        migrations.DeleteModel(
            name='Actuator',
        ),
    ]
